POST http://127.0.0.1:8080/rotate-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTkxMTc4NTMsImlhdCI6MTY5OTAzMTQ1MywiaXNzIjoic2NpX3JldmlldyIsImp0aSI6IjdlODMyZjM3LWY2OWMtNDA5Mi1hM2FjLWUyM2Q3OWRhZTNlZCIsInN1YiI6IjVhYjQ4Yjk0LWRlMzUtNDc1OS1hMzU5LWYwYzBmZjVlZTU0YyJ9.UEcgQf17w2TLyTT_SrEqW9zSeMCvirz642pDcQt1uNY"
}