POST http://127.0.0.1:8080/rotate-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTkwMzA3MDgsImlhdCI6MTY5OTAyMDcwNSwiaXNzIjoic2NpX3JldmlldyIsImp0aSI6Ijc2ZGE4YmIwLTEwMTQtNDllZS04N2VhLWIyMmIyZWVhZDkzNSIsInN1YiI6IjM1OGM1YTBkLWJhZTktNGNlZi1hOTkzLTM0MGMyNDRmYTcyMCJ9.mQQbPTIPLZGUUEFWCwbP3IkJ1LTbw2tI07kFg6WPOSU"
}